data = [["Salut",0],["Bonjour",0],["Bonsoire",0],["Hello",0],["coucou",0],["ça va",0],["slt",0],["cc",0],
["Quel est ton nom.",1],["qu'est-ce que tu es",1],["qui es-tu",1],["ton nom s'il te plaît",1],
["Bye",2],["A plus tard",2],["Au revoir",2],["Ravi d'avoir discuté avec toi, bye",2],["A la prochaine fois",2],["Non",2],
["Merci",3],["C'est utile",3],["Génial, merci",3],["Merci de m'avoir aidé",3],
[" m'aider",4],["fonctionne ",4],["fonctionne-tu ",4],["faire",4],["aide fournis-tu",4],[" es-tu utile",4],["soutien offre-tu ",4],[" sais-tu ",4],["s'agit-il ",4],
["entreprise ou la direction",5],["direction",5],["entreprise",5], ["d'entreprise",5],
["oui",6],["d'accord",6],["yes",6],
["Travail  sur écran ",7],["travail  sur écran ",7],
["Service de gardiennage ",8],["service de gardiennage ",8],
["Magasin ",9],["magasin ",9],
["Entretien des locaux ",10],["entretien des locaux ",10],
["désinsectisation",11],["dératisation",11],
[" vidanges des fosses",12],[" vidange de fosse",12],
["déchets",13],["évacuation des déchets",13],
[" manutentions des objets",14],
["produits chimiques",15],
[" travail sur l'écran",16],
["l'écran",17],
["écran",18],
["d'écran",19],
["travail sur écran",20],
["terrassement",21],
["oui",22],["d'accord",22],["yes",22],
["Décapage",23],["Décapage végétale",23],
["Déblaiement, Nivellement du sol ",24],
["Remblai et compactage",25],
["EPI pour la circulation sur chantier",26],
["circulation sur chantier",27],["circulations chantiers",27],
["circulation engins",28],
["éboulement, collision engin-engin, engin-personne",29],["engin-personne",29],["éboulement",29],["collision",29],["d'éboulement",29],["d'éboulements",29],["éboulements",29],
["chutes de déblais",30],["chutes de Gravats",30],["chutes de  déblais/Gravats",30],
["le dégagement des gaz nocifs ou toxiques, poussières",31],["gaz nocifs ou toxiques, poussières",31],["gaz nocifs",31],["gaz toxiques",31],["poussières",31],
["vibrations et nuisances sonnores",32],["nuisances sonnores",32],["troubles auditives",32],["bruit",32],
["l'électrocution, électrisation",33],["électrisation",33],["électrocution",33],["d'électrocution",33],["d'électrisation",33],["l'électrocutions, électrisations",33],["électrisations",33],["électrocutions",33],["d'électrocutions",33],["d'électrisations",33],
["EPI pour le travail en milieu chaud",34],["EPI en milieu chaud",34],["EPI milieu chaud",34],
["Quel EPI pour le travail en milieu froid",35],["Quel EPI pour les travaux en milieu froid",35],["EPI milieu froid",35],
["thermique",36],["thermiques",36],
[" fouille",37],["fouilles",37],
["Excavation",38],["d'excavation",38],["excavations",38],
["Evacuation de la terre",39],["d'évacuation de la terre",39],["évacuations terre",39],
["éboulement fouille",40],
["collision Engin-personnes, Engin-Engin",41],["collision Engin-personnes",41], ["collision  Engin-Engin",41], ["collision  d'engin",41], ["collision engin",41],
["chutes d'engin",42],["chute engin",42],
["ensevelissements",43],["d'ensevelissements",43],["ensevelissement",43],
["intoxications gaz nocifs, explosifs, toxiques ",44],["d'intoxications de gaz nocifs, explosifs, toxiques ",44],
["chutes de déblais",45],[" chutes d'objets sur les travailleurs ",45],
["troubles musculosquelettiques",46],["trouble musculosquelettique",46],["Troubles musculosquelettiques",46],["Trouble musculosquelettique",46],["Trouble musculosqueletique",46],
["écrasement, coincement sous l'engin ",47],["coincement sous l'engin ",47], ["écrasement",47],["d'écrasement",47],
["fondation",48],
["feraillage ",49],
["Coffrage",50],
["Bétonnage",51],["bétonnage",51],["Betonnage",51],["betonnage",51],
["projection des particules dans les yeux ",52],["particules dans les yeux ",52],
["travail dans la fosse",53],
["inhalation des débrits de fer",54],["débrits de fer",54],
["postures contraignantes",55],
["chutes de plain-pied",56],
["projection du béton",57],
["douleurs aux articulations liés à l'utilisation du vibreur",58],[" douleurs aux articulations",58],
["troubles auditives",59],
["feraillage",60],
["Cisailler les barres et Plier les barres.",61],
["Assembler des barres",62],
["espace de travail encombré ",63],["d'espace de travail encombré ",63],
["particules de métal et du matériel ",64],
["coffrage",65],
["EPI travail électrique",66],
["chocs électriques, Electrisation, Electrocution",67],["électriques, Electrisation, Electrocution",67],
[" EPI coffrage",68],
["travail en hauteur",69],["chute de personne",69],["chutes de personne",69],["Chutes de personne",69],
["éffondrements ou écroulements des pannaux de coffrage ",70],["écroulements des pannaux de coffrage ",70],["éffondrements des pannaux de coffrage ",70],["d'éffondrements des pannaux de coffrage ",70],
["utilisation du matériel ou outils ",71],["Blessures",71],["blessures",71],["blessure",71],["Blessure",71],
["contacts électriques",72],
["dallage",73],["dallages",73],
["travaux d'élevation",74],["élevation",74],["d'élevation",74],["élevations",74],
["couverture",75],["couvertures",75],["toitures",75],["Toitures",75],["toiture",75],["Toiture",75],
["Atteinte occulaires",76],["Atteinte occulaire",76],["atteinte occulaire",76],["Refraction de la lumière par les tolles",76],
["Travail avec du courant électrique",77],
["Plomberie",78],["plomberie",78],
["Flamme de chalumeau, soudage à l'arc",79],["Brûlure, incendie, explosion",79],["incendie",79],["d'incendie",79],["l'incendie",79],["Produits inflammables ",79],["produit inflammable",79],
["Travail avec l'électricité",80],["Electrocution, Electricité",80],["électrocution, électricité",80],["électrocutions, électricités",80],["électrocution,électricité",80],["Electrocutions,Electricités",80],
["Espace encombré",81],["Chute de plain-pied",81],["espace encombré",81],["chute de plain-pied",81],["espaces encombrés",81],
["Dégagement des poussières",82],["Inhalation des poussières",82],["dégagement de poussière",82],["inhalation de poussière",82],
["Niveau de bruit supérieur à 85 dBA",83],["Troubles auditives",83],["niveau de bruit supérieur à 85 dBA",83],["trouble auditive",83],
["Application de colles ou de solvants (colle PVC, résines époxy…)",84],["Inhalation des produits chimiques",84],["colle PVC, résines époxy",84],["inhalation des produits chimiques",84],["produits chimiques",84],["produit chimique",84],["application de colles ou de solvants",84],
["Utilisation de produits corrosifs (soude caustique, acide chlorhydrique...)",85],["Atteinte à la peau",85],["utilisation de produits corrosifs",85],["atteinte à la peau",85],["produits corrosifs",85],["atteintes à la peau",85],["produit corrosif",85],
["Ambiances thermiques",86],["baisse de la précision",86],["ambiances thermique",86],["baisses de précision",86],
["Crépissage",87],["crépissage",87],["Crépissages",87],["crépissages",87],
["Utilisation du marteau et de la truelle",88],["utilisation du marteau et de la truelle",88],["d'utilisation marteau  truelle",88],
["Projection du mortier",89],["projection mortier",89],
["Dégagement de la poudre du ciment",90],["dégagement  poudre du ciment",90],
["Gestes répétitifs",91],["geste répétitif",91],
["Etanchiété",92],["étanchiété",92],["d'étanchiété",92],
["utilisation chalumeau",93],["Utilisation du chalumeau",93],
["Exposition à la chaleur",94],["exposition chaleur",94],["d'exposition chaleur",94],
["Exposition au froid",95],["exposition froid",95],["d'exposition froid",95],
["Manutention des charges lourdes",96],["manutention charges lourdes",96],
["Carrelage",97],["carellage, carellages",97],
["Sol glissant",98],["sol glissant",98],["sol glisse",98],
["produits d'entretien( détergent, décapant, dégraissants)",99],["produits d'entretien",99],
["Des cables qui trainent au sol",100],["cables qui trainent au sol",100],["cable  traine  sol",100],["cable nu",100],["cable exposé",100],["cable,câble",100],["cables,câbles",100],["exposition de cable",100],
["Déplacement sur des escaliers",101],["déplacement escalier",101],["déplacements escaliers",101],["escaliers",101],["d'escaliers",101],["escalier",101],["d'escalier",101],
["produits dangéreux (bitume, les colles et vernis)",102],["Trouble respiratoire",102],["troubles respiratoires",102],["Troubles respiratoires",102],["trouble respiratoire",102],["fibres laines d'isolation",102],["fibre laine d'isolation",102],["Poussières d'amiante et de silice",102],["amiante silice",102],["poussières de ciment",102],["poussières de ciment",102],
["Irritation des yeux",102],["irritation yeux",102],["irritation oeil",102],["Irritation cutanée",102],["Nocives par inhalation",102],["nocives inhalation",102],["Lésions pulmonaires",102],["lésion poumon",102],["affections occulaires",102],["affection occulaire",102],
["Utilisation du matériel électrique (Carrellette, mixeur)",103],["Carrellette, mixeur",103],
["Carrellette, mixeur",103],
["Pose de carreaux en hauteur",104],["pose carreaux hauteur",104],
["Ambiances thermiques des chantiers en intérieur ou en extérieur.",105],
["Placo",106],["placo",106],["Placo-plâtre",106],["placo-plâtre",106],
["Manutention",107],["Lombalgie, Hernie discale",107],
["Douleurs lombaires",108],["douleur lombaire",108],
["Découpe du plâques",109],["découpe plâque",109],["Coupures",109],["coupure",109],["Découpe du plaques",109],["découpe plaque",109],
["Douleurs articulaires",110],["douleur articulaire",110],
["Utilisation des produits chimiques",111],["Inhalation des produits chimiques",111],["inhalation produit chimique",111],
["Dégagement des particules",112],["dégagement particule",112],["Inhalation des poussières des matériaux",112],["inhalation poussière matériaux",112],["plaques de plâtres, laine de verre, laine de roche, polystyrène, produits isolants.",112],
["Travail avec des installations électriques",113],["travail  installation électrique",113],
["Peinture",114],["peinture",114],["peintures",114],
["Produits inflammables peinture",115],["produit inflammable peinture",115],["produit inflammable peinture",115],["incendie, explosion peinture",115],
["Utilisation du matériel (cutters, ciseaux, gratoire)",116],["utilisation matériel cutters, ciseaux, gratoire",116],["Blessures, coupure",116],
["glissade",117],["Glissade",117],["glissades",117],["Glissades",117],
["Atteinte de la peau (Brûlure)",118],["atteinte  peau",118],["Atteintes  peau",118],
["chutes hauteurs",119],["chute hauteur",119],["Chutes de hauteur",119],["chute de hauteur",119],["Chute de hauteur",119],["Travaux en hauteur",119],["Travaux  hauteur",119],["travaux en hauteur",119],["travaux  hauteur",119],["Travaux en hauteur",119],["Travail hauteur",119],["travail en hauteur",119],["travail  hauteur",119],
["EPI de travail en hauteur",120],["EPI de travaux en hauteur",120],["EPI hauteur",120],
["non habilitation des travaux en hauteur",121],["non habileté travaux e hauteur",121],[" personne non habileté travail hauteur",121],
["évaluation travail en hauteur",122],["évaluer travaux en hauteur",122],["planifié travaux en hauteur",122],["planifier travaux en hauteur",122],["organiser travaux en hauteur",122],["organisé travaux en hauteur",122],["planification travaux en hauteur",122],["organisation travaux en hauteur",122],["planification travail en hauteur",122],["organisation travail en hauteur",122],
["règle travaux hauteur",123],["règle travail hauteur",123],["règles travaux hauteur",123],["règles travail hauteur",123],["règles de sécurité travail hauteur",123],
["travail avec des engins et des véhicules au chantier",124], ["travail engins  véhicules  chantier",124],["Travail engin  véhicule  chantier",124],
["Grue à tour",125],["grue à tour",125],["utilisation grue à tour",125],["Utilisation grue à tour",125],["règle sécurité grue à tour",125],
["Grue mobile",126],["grue mobile",126],["utilisation grue mobile",126],["Utilisation grue mobile",126],["règle sécurité grue mobile",126],
["Travail électricité",127],["Travaux électricité",127],["travail électricité",127],["travaux électricité",127],["Travail électrique",127],["Travaux électrique",127],["travail électrique",127],["travaux électrique",127],
["EPI soudure",128],["EPI soudage",128],
["Construction métallique",129],["Constructions métalliques",129],["construction métallique",129],["constructions métalliques",129],
["Eblouissement",130],["éblouissement",130],["Eblouissements",130],["éblouissements",130],
["Fuite de Gaz chalumeau",131],["fuite de Gaz chalumeau",131],["Fuites  Gaz chalumeau",131],["fuites  Gaz chalumeau",131],
["Maintenance",132],["maintenance engin véhicule",132],["maintenance engins véhicules",132],
["Rayonnement UV",133],["rayonnement UV",133],["Rayonnements UV",133],["rayonnements UV",133],
["Inhalation des fumées et des gaz nocifs",134],["inhalation fumées  gaz nocifs",134],["d'inhalation fumées  gaz nocifs",134],["Inhalations des fumées et des gaz nocifs",134],["inhalations fumées  gaz nocifs",134],["d'inhalations fumées  gaz nocifs",134],
["Meule en activité",135],["meule activité",135],
["Tension électrique",136],["tensions électriques",136],
["Brûlure ",137],["brûlure ",137],["Brûlures ",137],["brûlures ",137],["Brulure ",137],["brulure ",137],["Brulures ",137],["brulures ",137],
["Cécité traumatisme oculaires",138],["projection  yeux",138],
["Travaux en espace confiné",139],["travaux espace confiné",139],
["Surdité",140],["Bruits",140],["surdité",140],["bruit",140],
["Descente dans des puits",141],["descente  puits",141],["chute",141],
["Exposition chaleur froid",142],["exposition chaleur froid",142],
["contamination cutanéo-muqueuse",143],["Infections parasitaire",143],["contaminations cutanéo-muqueuse",143],["infection parasitaire",143],
["Incendie/Explosion",144],["incendie explosion",144],["incendies explosions",144],
["Electrocution/Electrisation",145],["Electrocutions Electrisations",145],["electrocution electrisation",145],["electrocutions electrisations",145],
["Asphyxie, Intoxication espace confiné",146],["asphyxie, intoxication  espace confiné",146],
["Etouffement espace confiné",147],["etouffement  espace confiné",147],
["Engoisse panique espace confiné",148],["engoisses paniques espace confiné",148],
["Circulation sur chantier",149],["circulation sur chantier",149],
["Coactivité",150],["coactivité",150],["Coactivités",150],["coactivités",150],["Co-activité",150],["co-activité",150],["Co-activités",150],["co-activités",150],
["Mission professionnelle sur trajet",151],["mission professionnel trajet",151],
["Collision véhicules",152],["collision véhicule",152],["Collisions véhicules",152],["collisions véhicule",152],
["Manutention manuelle",153],["manutentions manuelles",153],["manutention manuelle",153],
["Risques chimiques",154],["risques chimiques",154],["Risque chimique",154],["risque chimique",154],
["Néttoyage à pression",155],["néttoyage à pression",155],["Jet très haute pression",155],["jet très haute pression",155],
["HSE hse Hse",156],["HSE",156],["hse",156],["Hse",156]]
